export const QDRANT_API_URL = "YOUR API KEY HERE"
export const QDRANT_API_KEY = "YOUR API KEY HERE"
export const QDRANT_URL_PORT = 6333
export const QDRANT_COLLECTION_NAME="YOUR COLLECTION NAME"
export const OPENAI_API_KEY = "YOUR API KEY HERE"